### ISSUE TITLE
Image upload issue

### ISSUE THREAD

**Issue by SudarshanGGD** [garbhagudi/garbhagudi-next#1023]
Hi sir, 

Can't upload new images to the website. We can only replace with existing images. Please resolve is ASAP.

Thank you

**Comment by snorflux** [comment]
<img width="1110" alt="image" src="https://github.com/user-attachments/assets/a857f35c-f853-4fc1-a579-af0a59e6d557">

I am not able to reproduce this issue. Can you show me what the error is or provide more than 1 line of information.
