### ISSUE TITLE
Add the Appointment solution Production Link to GarbhaGudi Website

### ISSUE THREAD

**Issue by HNPavan** [garbhagudi/garbhagudi-next#771]
Dear Avinash

Please find the Appointment solution Production Link to the GarbhaGudi Website

Production Link - https://medicsprime.in/OnlineAppointment/OnlineAppointment.jsp?enx=%7B%22e%22%3A%22Pv1yAd9b5VMo2DOud8JSJFkU7CzPOXXBQlPNffirhwA6fe2HHci3dR%2BT1cnBNmqH3kNc2wKJoqqIdPgk0Ie7iA%3D%3D%22%2C%22s%22%3A%22f5ec95cc090eb4a5273afdb7946feb74%22%2C%22i%22%3A%22d919f6d46ee942475fcf1bd0928d6b47%22%7D

**Comment by dbugging404** [comment]
> Dear Avinash
> 
> Please find the Appointment solution Production Link to the GarbhaGudi Website
> 
> Production Link - https://medicsprime.in/OnlineAppointment/OnlineAppointment.jsp?enx=%7B%22e%22%3A%22Pv1yAd9b5VMo2DOud8JSJFkU7CzPOXXBQlPNffirhwA6fe2HHci3dR%2BT1cnBNmqH3kNc2wKJoqqIdPgk0Ie7iA%3D%3D%22%2C%22s%22%3A%22f5ec95cc090eb4a5273afdb7946feb74%22%2C%22i%22%3A%22d919f6d46ee942475fcf1bd0928d6b47%22%7D

Link added and moved to prod. 

Check and let me know if there are any issues,

**Comment by HNPavan** [comment]
Please remove the production link from the website and integrate the form.
