### ISSUE TITLE
Requesting to create new pages with the provided URLs

### ISSUE THREAD

**Issue by SudarshanGGD** [garbhagudi/garbhagudi-next#783]
Dear sir,

As per changes suggested by Catalysts I'm requesting you to create new web pages. Please check with the below link for the suggested URLs.

(https://docs.google.com/spreadsheets/d/16kMvqs-KhgbYqBfJzKFL8uPm-S9CGShezZjlSlg9mjU/edit#gid=1245515903)

Thank you

**Comment by dbugging404** [comment]
Checked the excel. 

You are asking me to move the location pages to the treatment route. This is very much not recommended. Please confirm once again. 

This can be done, But will take reconstruction of the entire location and treatment routes and will create confusion within the project.

**Comment by dbugging404** [comment]
closing the issue. reopen if necessary.
