### ISSUE TITLE
Logo issue in career page

### ISSUE THREAD

**Issue by SudarshanGGD** [garbhagudi/garbhagudi-next#821]
Hi sir, GGIRHR logo is not reflecting on career page. Even though GGIRHR logo is attached, GarbhaGudi logo is reflecting in the page. Kindly look into it resolve the issue.

Please check the screenshots
![Screenshot 2024-05-03 162119](https://github.com/garbhagudi/garbhagudi-next/assets/163981310/92c73368-9363-49e5-ac61-c6c85139eca1)
![Screenshot 2024-05-03 162047](https://github.com/garbhagudi/garbhagudi-next/assets/163981310/7188c314-8da8-4d4b-a305-11d5a7d53f04)

Thank you

**Comment by dbugging404** [comment]
Done. 

Better Images needed. Pls use the GG emblem logo provided here in SVG/PNG not JPG

https://www.garbhagudi.com/contact/media-kit 

GGIRHR emblem is not available, pls get it done from Manju sir.
