### ISSUE TITLE
Publications page issue

### ISSUE THREAD

**Issue by SudarshanGGD** [garbhagudi/garbhagudi-next#866]
Hi sir,

CMS change on Publications page is not reflecting on the website. Kindly look into it and resolve ASAP.

Thank you.

**Comment by dbugging404** [comment]
<img width="1206" alt="image" src="https://github.com/garbhagudi/garbhagudi-next/assets/73649710/0540871d-b3fa-407c-b39e-466562b3bfb8">


While adding content add all the fields. Or it will throw error and reflect the changes. 

It is a failsafe to not let incomplete content appear on the website.

**Comment by dbugging404** [comment]
same for all fields. If you don't complete all the fields. changes will not be reflected, in any module.
