### ISSUE TITLE
Adding NABH logo

### ISSUE THREAD

**Issue by SudarshanGGD** [garbhagudi/garbhagudi-next#867]
Hi sir,

Please add the NABH logo to EC, KN & HN locations on the website.

PFA of logo.
![NABH-01](https://github.com/garbhagudi/garbhagudi-next/assets/163981310/3642510f-1c96-476e-857c-f50518e5de79)
![NABH-01](https://github.com/garbhagudi/garbhagudi-next/assets/163981310/7187d1ed-8fce-45e6-b592-6435f19e12f2)

**Comment by garbhagudi** [comment]
done. Will be pushed to prod with other updates.
