### ISSUE TITLE
LP clone

### ISSUE THREAD

**Issue by SudarshanGGD** [garbhagudi/garbhagudi-next#976]
Hi sir, please look into the attached image and link and please finish it ASAP.

![WhatsApp Image 2024-09-02 at 12 10 58 PM](https://github.com/user-attachments/assets/98077717-8e26-45a6-a03e-d3d08731288e)

https://www.garbhagudi.com/lp/ivf-enquiry-form

Thank you.

**Comment by snorflux** [comment]
Comment with the URL you need for the LP ? 

What form to use ? Do you have a new form ? or do I have to use the same form ? How will you know its form this campaign ?
